---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-config
  namespace: myns
data:
  TZ: 'Asia/Singapore'
  DEFAULT_WORKSPACE: '/config/workspace'
  PROXY_DOMAIN: 'code-137.184.249.123.nip.io'

---
apiVersion: v1
kind: Secret
metadata:
  name: cs-secret
  namespace: myns
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: c3Vkb3Bhc3N3b3Jk

--- 
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: cs-deploy 
  namespace: myns
  labels:
    app: codeserver 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      name: cs-pod
      labels:
        app: codeserver
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: cs-pvc
      containers:
      - name: cs-containers 
        image: linuxserver/code-server:4.99.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: data-vol
            mountPath: /config/workspace
        envFrom:
          - configMapRef:
              name: cs-config
          - secretRef:
              name: cs-secret
        ports:
        - name: cs-port 
          containerPort: 8443
        resources:
          requests:
            cpu: 512m # 1 CPU is 1000m
            memory: 256Mi # usually need about 2GB memory to do development
          limits: 
            cpu: 512m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: myns
  labels:
    app: codeserver
spec:
  type: ClusterIP
  selector:
    app: codeserver
  ports:
  - name: cs-port
    port: 8443