---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dov
      env: prod
  template:
    metadata:
      name: dov-pod
      labels:
        app: dov
        env: prod
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          valueFrom:
            configMapKeyRef:
              name: dov-config
              key: instance_name
        envFrom:
          - secretRef:
              # all the values in dov-secret will be set as env variables
              name: dov-secret
        ports:
          - name: dov-port
            containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov
spec:
  type: ClusterIP
  selector:
    app: dov
    env: prod
  ports:
    - name: dov-port # ok to be same value as container port name
      port: 8080 # can also be same as containerPort
      targetPort: dov-port # doesnt clash