# fly.toml app configuration file generated for csda-app on 2025-04-21T00:47:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'csda-app'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
