---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bggdb
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
      env: prod
  template:
    metadata:
      name: bgg-pod
      labels:
        app: bggdb
        env: prod
    spec:
      containers:
      - name: bggdb
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
          - name: bggdb-port
            containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb
    env: prod
spec:
  type: ClusterIP
  selector:
    app: bggdb
    env: prod
  ports:
    - name: bggdb-svc-port 
      port: 3306
      targetPort: bggdb-port